steps:
- id: 'Provision Voice Components'
  name: 'gcr.io/$PROJECT_ID/privateedition'
  entrypoint: 'bash'
  args: ['services/provision-voice.sh']
  timeout: '3600s'
  env:
    - 'VDOMAIN=${_VDOMAIN}'
    - 'VGCPPROJECT=${_VGCPPROJECT}'
    - 'VGCPREGION=${_VGCPREGION}'
    - 'VGKECLUSTER=${_VGKECLUSTER}'
    - 'VHELMCOMMAND=${_VHELMCOMMAND}'
    - 'VIMAGEREGISTRY=${_VIMAGEREGISTRY}'
    - 'VARTIFACTREPO=${_VARTIFACTREPO}'
timeout: '3600s'