###############################################################################
# Global UCSX image parameters
# https://all.docs.genesys.com/UCS/Current/UCSPEGuide/Configure
###############################################################################

replicaCount: 1

image:
  registry: $IMAGE_REGISTRY
  # repository: ucsx/ucsx  
  pullPolicy: IfNotPresent
  pullSecrets: 
    - name: pullsecret

resources:
  limits:
    cpu: 2000m
    memory: 1000Mi
  requests:
    cpu: 300m
    memory: 500Mi

existingSecret:
existingConfig:

gauth:
  auth:
    url: http://gauth-auth.gauth.svc
  env:
    url: http://gauth-environment.gauth.svc

service:
  enabled: true
  name: ucsx
  type: ClusterIP
  port: 8080
  env: {}
  annotations: {}

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  enabled: true
  hosts:
  - host: ucsx.${DOMAIN}
    paths:
    - path: /ucs/v3/
      port: 8080
    - path: /ucs/v10/
      port: 8080
    - path: /ucs/v3/config
      port: 8500
  tls:
  - hosts:
    - ucsx.${DOMAIN}
    secretName: ucsx-ingress-ext

# * Monitoring
monitoring:
  # Deploy ServiceMonitor
  enabled: true
  # Create PrometheusRule k8s object with alarm definitions
  alarms: true
  # Create ConfigMaps with Grafana Dashboards
  dashboards: true
